title: Notifiquei Pro
description: Crie, envie e agende notificações locais personalizadas.
url: "[https://seu-usuario.github.io](https://seu-usuario.github.io)"

# Configurações Comerciais e Administrativas
pix:
  price: "48,90"
  key: "00020126580014BR.GOV.BCB.PIX..."
  admins:
    - "tfagro2023@gmail.com"
    - "kauaesuelen03@gmail.com"

# Credenciais do Console Firebase
firebase:
  apiKey: "SUA_API_KEY"
  authDomain: "seu-app.firebaseapp.com"
  projectId: "seu-app"
  storageBucket: "seu-app.appspot.com"
  messagingSenderId: "123456789"
  appId: "1:123456789:web:abcdef"
  
