title: Notifiquei Pro
description: Crie, envie e agende notificações locais personalizadas.
url: "[https://amorim08kaua-ship-it.github.io/Pro-3/](https://amorim08kaua-ship-it.github.io/Pro-3/)"

# Configurações Comerciais e Administrativas
pix:
  price: "48,90"
  key: "tfagro2023@gmail.com"
admins:
    - "tfagro2023@gmail.com"
    - "kauaesuelen03@gmail.com"

# Credenciais do Console Firebase
firebase:
  apiKey: "SUA_API_KEY"
  authDomain: "seu-app.firebaseapp.com"
  projectId: "seu-app"
  storageBucket: "seu-app.appspot.com"
  messagingSenderId: "123456789"
  appId: "1:123456789:web:abcdef"
  
